##
 # @file mk/make.py
 # @date 2026/08/07
 # 
 # @brief Makefile-style build entry for Dandelion (Nuitka standalone).
 #
 # @usage
 #   python mk/make.py            : full build (same as 'all')
 #   python mk/make.py clean      : remove runtime caches and build artifacts
 #   python mk/make.py all        : build standalone executable into build/
 #   python mk/make.py version    : print project name and version
 #   python mk/make.py sign       : sign Windows executable (placeholder)
 #

import configparser
import datetime
import importlib.util
import os
import platform
import shlex
import shutil
import subprocess
import sys
import tomllib

##
 # @brief Directory of this script (mk/).
 #
MK_DIR = os.path.dirname(os.path.abspath(__file__))

##
 # @brief Project root directory (parent of mk/).
 #
ROOT_DIR = os.path.dirname(MK_DIR)

##
 # @brief Usage help text.
 #
USAGE = """Usage: python mk/make.py [target]

Targets:
  (none)   : full build (same as 'all')
  all      : build standalone executable into build/
  clean    : remove runtime caches and build artifacts
  version  : print project name and version
  sign     : sign Windows executable (placeholder, P3)
  help     : show this help
"""

##
 # @brief Load mk/config/build.config (INI).
 #
 # @return configparser.ConfigParser instance.
 #
def _load_config():
    cfg = configparser.ConfigParser()
    cfg.read(os.path.join(MK_DIR, "config", "build.config"))
    return cfg
# End-def

##
 # @brief Load root pyproject.toml (TOML).
 #
 # @return dict parsed from pyproject.toml.
 #
def _load_pyproject():
    with open(os.path.join(ROOT_DIR, "pyproject.toml"), "rb") as f:
        return tomllib.load(f)
# End-with

##
 # @brief Get project name and version (single source of truth).
 #
 # @return (name, version) tuple.
 #
def _project_meta():
    meta = _load_pyproject()["project"]
    return meta["name"], meta["version"]
# End-def

##
 # @brief Check Nuitka availability in the current interpreter.
 #
def _check_nuitka():
    if importlib.util.find_spec("nuitka") is None:
        print("[-] Nuitka is not installed.")
        print("    Install with: pip install -e \".[dev]\"")
        sys.exit(1)
    # End-if
# End-def

##
 # @brief Generate mk/lib/build_info.py with build metadata.
 #
 # @param version Project version string.
 #
def _gen_build_info(version):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "##",
        " # @file mk/lib/build_info.py",
        " # @date " + now[:10],
        " # ",
        " # @brief Build metadata generated by mk/make.py. DO NOT EDIT.",
        " #",
        "",
        "VERSION = \"" + version + "\"",
        "BUILD_MODE = \"standalone\"",
        "BUILD_DATE = \"" + now + "\"",
        "PLATFORM = \"" + platform.system().lower() + "\"",
        "",
    ]
    path = os.path.join(MK_DIR, "lib", "build_info.py")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    # End-with
    print("[+] Generated " + os.path.relpath(path, ROOT_DIR))
# End-def

##
 # @brief Assemble and run the Nuitka standalone build.
 #
 # @param cfg     Build config (ConfigParser).
 # @param name    Project name (binary name).
 # @param version Project version string.
 #
def _run_nuitka(cfg, name, version):
    entry = os.path.join(ROOT_DIR, cfg.get("build", "entry", fallback="main.py"))
    output_dir = os.path.join(ROOT_DIR, cfg.get("build", "output_dir", fallback="build"))
    cache_dir = os.path.join(ROOT_DIR, cfg.get("build", "cache_dir", fallback=".nuitka-cache"))
    jobs = cfg.get("nuitka", "jobs", fallback="4")
    if sys.platform == "win32":
        # MSVC consumes large heap per compile unit; reduce parallelism to
        # avoid "C1002: compiler is out of heap space in pass 2".
        jobs = cfg.get("nuitka", "windows_jobs", fallback="2")
    # End-if
    extra_args = shlex.split(cfg.get("nuitka", "extra_args", fallback=""))

    cmd = [
        sys.executable, "-m", "nuitka",
        "--mode=standalone",
        "--output-dir=" + output_dir,
        "--output-filename=" + name,
        "--include-package=src",
        "--include-module=mk.lib.paths",
        "--include-module=mk.lib.build_info",
        "--assume-yes-for-downloads",
        "--jobs=" + jobs,
        "--static-libpython=no",
    ]

    # ----- @par Anti-Bloat Plugins & Deployment Flags -----
    cmd.append("--enable-plugin=anti-bloat")
    cmd.append("--noinclude-pytest-mode=nofollow")
    cmd.append("--noinclude-setuptools-mode=nofollow")
    cmd.append("--noinclude-unittest-mode=nofollow")
    cmd.append("--no-deployment-flag=excluded-module-usage")
    cmd.append("--no-deployment-flag=error-on-failed-import")

    # ----- @par Selective Compilation (Bypass C-Compilation) -----
    nofollow_str = cfg.get("nuitka", "nofollow_imports", fallback="")
    if nofollow_str:
        for pkg in [p.strip() for p in nofollow_str.split(",") if p.strip()]:
            cmd.append("--nofollow-import-to=" + pkg)
        # End-for
    # End-if

    # ----- @par Force Include Standard Modules -----
    std_mods_str = cfg.get("nuitka", "include_std_modules", fallback="")
    if std_mods_str:
        for mod in [m.strip() for m in std_mods_str.split(",") if m.strip()]:
            cmd.append("--include-module=" + mod)
        # End-for
    # End-if

    # ----- @par Windows-only options (PE version resource + icon) -----
    if sys.platform == "win32":
        company = cfg.get("build", "company", fallback="").strip()
        description = cfg.get("build", "description", fallback="").strip()

        if company:
            cmd.append("--company-name=" + company)
        # End-if
        if description:
            cmd.append("--file-description=" + description)
        # End-if

        cmd += [
            "--product-name=" + name,
            "--product-version=" + version,
            "--file-version=" + version,
        ]

        icon = os.path.join(ROOT_DIR, cfg.get("build", "icon", fallback="mk/config/dandelion.ico"))
        if os.path.exists(icon):
            cmd.append("--windows-icon-from-ico=" + icon)
        # End-if
    # End-if

    # ----- @par Extra user args -----
    cmd += extra_args

    # ----- @par Entry script -----
    cmd.append(entry)

    env = os.environ.copy()
    env["NUITKA_CACHE_DIR"] = cache_dir

    print("[*] Executing: " + " ".join(cmd))
    print("[*] Nuitka Cache Dir: " + cache_dir)
    result = subprocess.run(cmd, cwd=ROOT_DIR, env=env)
    if result.returncode != 0:
        print("[-] Build failed with exit code " + str(result.returncode))
        sys.exit(result.returncode)
    # End-if
# End-def

##
 # @brief Copy a single python package/module and its dist-info metadata.
 #
 # @param import_name Top-level import name (e.g. 'pydantic_core').
 # @param dist_name   Canonical distribution name (e.g. 'pydantic-core').
 # @param dst_dir     Destination directory (bin/).
 # @param copied      Set of already-copied import names (dedup).
 #
def _copy_package(import_name, dist_name, dst_dir, copied):
    if import_name in copied:
        return
    # End-if

    spec = importlib.util.find_spec(import_name)
    if spec is None:
        return
    # End-if

    if spec.submodule_search_locations:
        src_dir = spec.submodule_search_locations[0]
        dst = os.path.join(dst_dir, import_name)
        # Ignore raw pyc caches to keep size small, Python will re-generate them at runtime if needed
        shutil.copytree(src_dir, dst, dirs_exist_ok=True, ignore=shutil.ignore_patterns("__pycache__"))
    elif spec.origin:
        dst = os.path.join(dst_dir, os.path.basename(spec.origin))
        shutil.copy2(spec.origin, dst)
    else:
        return
    # End-if
    copied.add(import_name)
    print("  [+] Copied package: " + import_name)

    # Also copy the .dist-info metadata so importlib.metadata lookups
    # (e.g. requests version checks) work at runtime.
    try:
        import importlib.metadata as imeta
        dist = imeta.distribution(dist_name)
        dst_info = os.path.join(dst_dir, os.path.basename(str(dist._path)))
        if not os.path.exists(dst_info):
            shutil.copytree(str(dist._path), dst_info, ignore=shutil.ignore_patterns("__pycache__"))
        # End-if
    except Exception:
        pass
    # End-try
# End-def

##
 # @brief Recursively copy a dependency closure from the current python env.
 #
 # @param roots   Root import names (e.g. 'anthropic', 'google').
 # @param dst_dir Destination directory (bin/).
 #
def _copy_dependency_closure(roots, dst_dir):
    import importlib.metadata as imeta
    import re

    # Reverse index: import name -> canonical dist names.
    import_to_dists = {}
    for imp, dists in imeta.packages_distributions().items():
        for d in dists:
            import_to_dists.setdefault(imp, []).append(d.replace("_", "-").lower())
        # End-for
    # End-for

    # BFS over distribution dependencies, starting from the root import names.
    queue = []
    for imp in roots:
        dists = import_to_dists.get(imp)
        if dists:
            queue.extend(dists)
        else:
            queue.append(imp.replace("_", "-").lower())
        # End-if
    # End-for

    seen = set()
    copied = set()
    while queue:
        dist = queue.pop(0)
        if dist in seen:
            continue
        # End-if
        seen.add(dist)

        try:
            reqs = imeta.requires(dist)
        except imeta.PackageNotFoundError:
            reqs = []
        # End-try

        for req in reqs or []:
            marker = req.split(";", 1)[1] if ";" in req else ""
            if "extra" in marker:
                continue
            # End-if
            name = re.split(r"[<>=!\[; ]", req)[0].strip()
            if name:
                queue.append(name.replace("_", "-").lower())
            # End-if
        # End-for

        # Copy every top-level import name provided by this distribution.
        imps = [imp for imp, dists in import_to_dists.items() if dist in dists]
        for imp in imps:
            _copy_package(imp, dist, dst_dir, copied)
        # End-for
    # End-for

    # Fallback: ensure the roots themselves were copied (e.g. single modules).
    for imp in roots:
        if imp not in copied:
            _copy_package(imp, imp.replace("_", "-").lower(), dst_dir, copied)
        # End-if
    # End-for
# End-def

##
 # @brief Copy stdlib modules imported by the bypassed packages into bin/.
 #
 # Bypassed packages are not analyzed by Nuitka, so stdlib modules they
 # import (e.g. zoneinfo) may be missing from the artifact. Scan the copied
 # sources and copy the needed stdlib modules as an on-disk fallback.
 # Iterates to fixpoint so transitive stdlib imports (e.g. ssl -> _ssl)
 # are covered as well.
 #
 # @param bin_dir Destination directory (bin/).
 #
def _copy_stdlib_fallback(bin_dir):
    import ast
    import sys as _sys

    stdlib_names = set(_sys.stdlib_module_names)
    copied = set()
    changed = True
    rounds = 0

    while changed and rounds < 10:
        changed = False
        rounds += 1
        found = set()

        # Collect stdlib top-level imports from all copied .py sources.
        for dirpath, dirnames, filenames in os.walk(bin_dir):
            if "__pycache__" in dirnames:
                dirnames.remove("__pycache__")
            # End-if
            for fn in filenames:
                if not fn.endswith(".py"):
                    continue
                # End-if
                path = os.path.join(dirpath, fn)
                try:
                    with open(path, "r", encoding="utf-8", errors="ignore") as f:
                        tree = ast.parse(f.read())
                    # End-with
                except Exception:
                    continue
                # End-try
                for node in ast.walk(tree):
                    if isinstance(node, ast.Import):
                        for alias in node.names:
                            top = alias.name.split(".")[0]
                            if top in stdlib_names:
                                found.add(top)
                            # End-if
                        # End-for
                    elif isinstance(node, ast.ImportFrom) and node.module:
                        top = node.module.split(".")[0]
                        if top in stdlib_names:
                            found.add(top)
                        # End-if
                    # End-if
                # End-for
            # End-for
        # End-for

        # Copy newly discovered stdlib modules.
        for mod in sorted(found):
            if mod in copied:
                continue
            # End-if
            spec = importlib.util.find_spec(mod)
            if spec is None:
                continue
            # End-if
            if spec.submodule_search_locations:
                src = spec.submodule_search_locations[0]
                dst = os.path.join(bin_dir, mod)
                shutil.copytree(src, dst, dirs_exist_ok=True, ignore=shutil.ignore_patterns("__pycache__"))
            elif spec.origin and spec.origin not in ("built-in", "frozen"):
                dst = os.path.join(bin_dir, os.path.basename(spec.origin))
                if os.path.exists(dst):
                    copied.add(mod)
                    continue
                # End-if
                shutil.copy2(spec.origin, dst)
            else:
                continue
            # End-if
            copied.add(mod)
            changed = True
            print("  [+] Stdlib fallback: " + mod)
        # End-for
    # End-while
# End-def

##
 # @brief Post-process Nuitka output into build/<name>/ layout.
 #
 # @param cfg     Build config (ConfigParser).
 # @param name    Project name (binary name).
 # @param version Project version string.
 #
def _postprocess(cfg, name, version):
    output_dir = os.path.join(ROOT_DIR, cfg.get("build", "output_dir", fallback="build"))
    entry = os.path.join(ROOT_DIR, cfg.get("build", "entry", fallback="main.py"))
    entry_base = os.path.splitext(os.path.basename(entry))[0]

    # Nuitka names the dist folder after the entry script (e.g. main.dist),
    # while --output-filename only controls the executable name inside it.
    dist_dir = os.path.join(output_dir, entry_base + ".dist")
    if not os.path.isdir(dist_dir):
        # Fallback: scan for a single *.dist folder in the output dir.
        if os.path.isdir(output_dir):
            candidates = [
                d for d in os.listdir(output_dir)
                if d.endswith(".dist") and os.path.isdir(os.path.join(output_dir, d))
            ]
            if len(candidates) == 1:
                dist_dir = os.path.join(output_dir, candidates[0])
            elif len(candidates) > 1:
                print("[-] Ambiguous Nuitka outputs: " + ", ".join(candidates))
                sys.exit(1)
            # End-if
        # End-if
    # End-if

    if not os.path.isdir(dist_dir):
        print("[-] Expected Nuitka output not found: " + dist_dir)
        sys.exit(1)
    # End-if

    # Rename <entry>.dist -> <name>/bin (C-style output layout).
    target_dir = os.path.join(output_dir, name)
    if os.path.isdir(target_dir):
        shutil.rmtree(target_dir)
    # End-if
    os.makedirs(target_dir)
    
    # Move the entire dist directory into the bin/ subfolder
    bin_dir = os.path.join(target_dir, "bin")
    os.rename(dist_dir, bin_dir)

    # ----- @par 1. Copy bypassed heavy packages (recursive dependency closure) -----
    copy_pkgs_str = cfg.get("nuitka", "copy_packages", fallback="")
    if copy_pkgs_str:
        roots = [p.strip() for p in copy_pkgs_str.split(",") if p.strip()]
        _copy_dependency_closure(roots, bin_dir)
    # End-if

    # ----- @par 1b. Stdlib fallback for bypassed packages -----
    _copy_stdlib_fallback(bin_dir)

    # ----- @par 2. Create required workspace directories -----
    print("[*] Creating workspace layout...")
    workspace_dirs = [".env", "llm/memory", "llm/skill", ".log"]
    for d in workspace_dirs:
        d_path = os.path.join(target_dir, d.replace("/", os.sep))
        os.makedirs(d_path, exist_ok=True)
        # Create a tiny .keep file so Git or ZIP archives preserve the empty folders
        with open(os.path.join(d_path, ".keep"), "w") as f:
            f.write("")
        # End-with
    # End-for
    print("  [+] Created directories: .env, llm, .log")

    # Pre-fill .env/api.cfg from the example template if present.
    env_dir = os.path.join(target_dir, ".env")
    example_cfg = os.path.join(ROOT_DIR, ".env", "api.cfg.example")
    if os.path.exists(example_cfg):
        shutil.copy2(example_cfg, os.path.join(env_dir, "api.cfg"))
        keep = os.path.join(env_dir, ".keep")
        if os.path.exists(keep):
            os.remove(keep)
        # End-if
        print("  [+] Pre-filled: .env/api.cfg (from api.cfg.example)")
    else:
        print("  [-] Note: .env/api.cfg.example not found; .env kept as .keep")
    # End-if

    # ----- @par 3. Create fake entry (shell script / cmd wrapper) -----
    print("[*] Creating fake entry at package root...")
    if sys.platform == "win32":
        entry_cmd = os.path.join(target_dir, "dandelion.cmd")
        with open(entry_cmd, "w", encoding="ascii", newline="\r\n") as f:
            f.write('@echo off\n"%~dp0bin\\' + name + '.exe" %*\n')
        # End-with
        print("  [+] Created: " + entry_cmd)
    else:
        # Wrapper script: exec the real binary from bin/ directly.
        # Unlike a symlink, this avoids dual path resolution ($ORIGIN vs
        # Nuitka module dir) which proved unreliable on Linux.
        entry_sh = os.path.join(target_dir, "dandelion.sh")
        content = (
            "#!/bin/sh\n"
            "SCRIPT_DIR=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n"
            "exec \"$SCRIPT_DIR/bin/" + name + "\" \"$@\"\n"
        )
        with open(entry_sh, "w", encoding="ascii", newline="\n") as f:
            f.write(content)
        # End-with
        os.chmod(entry_sh, 0o755)
        print("  [+] Created: " + entry_sh)

        # Force DT_RPATH (instead of DT_RUNPATH) so the bundled libs in bin/
        # (libpython etc.) are searched BEFORE LD_LIBRARY_PATH. Without this,
        # a foreign libpython from the environment can be loaded and crash
        # the binary (SystemError in codeobject).
        patchelf = shutil.which("patchelf")
        if patchelf:
            exe_path = os.path.join(bin_dir, name)
            result = subprocess.run(
                [patchelf, "--force-rpath", "--set-rpath", "$ORIGIN", exe_path],
                capture_output=True, text=True
            )
            if result.returncode == 0:
                print("  [+] RPATH forced on " + exe_path + ": $ORIGIN (before LD_LIBRARY_PATH)")
            else:
                print("  [-] Warning: patchelf failed: " + result.stderr.strip())
            # End-if
        else:
            print("  [-] Warning: patchelf not found; binary may be affected by LD_LIBRARY_PATH")
        # End-if
    # End-if

    # Write version file.
    with open(os.path.join(target_dir, "version.txt"), "w", encoding="utf-8") as f:
        f.write(version + "\n")
    # End-with

    # ----- @par 4. Strip pyc caches from the artifact -----
    for dirpath, dirnames, filenames in os.walk(target_dir):
        if "__pycache__" in dirnames:
            shutil.rmtree(os.path.join(dirpath, "__pycache__"), ignore_errors=True)
        # End-if
    # End-for

    exe_name = name + ".exe" if sys.platform == "win32" else name
    print("[+] Build success: " + os.path.join(bin_dir, exe_name))
    print("[+] Version file: " + os.path.join(target_dir, "version.txt"))
    print("[+] Nuitka intermediate kept at: " + os.path.join(output_dir, entry_base + ".build"))
# End-def

##
 # @brief Target: build standalone executable (default).
 #
def target_all():
    name, version = _project_meta()
    cfg = _load_config()

    mode = cfg.get("build", "mode", fallback="standalone").strip().lower()
    if mode != "standalone":
        print("[-] Unsupported build mode: " + mode + " (only 'standalone' is supported).")
        sys.exit(1)
    # End-if

    _check_nuitka()
    _gen_build_info(version)
    _run_nuitka(cfg, name, version)
    _postprocess(cfg, name, version)
# End-def

##
 # @brief Target: remove bytecode caches and build artifacts.
 #
def target_clean():
    print("[*] Cleaning bytecode caches...")
    removed = 0
    for dirpath, dirnames, filenames in os.walk(ROOT_DIR):
        if ".git" in dirnames:
            dirnames.remove(".git")
        # End-if
        if ".log" in dirnames:
            dirnames.remove(".log")
        # End-if
        if "__pycache__" in dirnames:
            shutil.rmtree(os.path.join(dirpath, "__pycache__"), ignore_errors=True)
            removed += 1
        # End-if
        for fn in filenames:
            if fn.endswith((".pyc", ".pyo")):
                os.remove(os.path.join(dirpath, fn))
                removed += 1
            # End-if
        # End-for
    # End-for
    print("[+] Removed " + str(removed) + " bytecode items.")

    # Remove build artifacts.
    cfg = _load_config()
    for key in ("output_dir", "cache_dir"):
        path = os.path.join(ROOT_DIR, cfg.get("build", key, fallback=""))
        if os.path.exists(path):
            shutil.rmtree(path, ignore_errors=True)
            print("[+] Removed " + os.path.relpath(path, ROOT_DIR))
        # End-if
    # End-for

    # Legacy dist/ directory.
    legacy = os.path.join(ROOT_DIR, "dist")
    if os.path.exists(legacy):
        shutil.rmtree(legacy, ignore_errors=True)
        print("[+] Removed dist/ (legacy)")
    # End-if
# End-def

##
 # @brief Target: print project name and version.
 #
def target_version():
    name, version = _project_meta()
    print("[+] " + name + " " + version)
# End-def

##
 # @brief Target: sign Windows executable (placeholder for P3).
 #
def target_sign():
    cfg = _load_config()
    enabled = cfg.getboolean("sign", "enabled", fallback=False)
    if not enabled:
        print("[-] Signing is disabled (mk/config/build.config [sign] enabled=false).")
        print("    Nothing to do.")
        return
    # End-if
    print("[-] Signing is not implemented yet (planned for P3).")
    sys.exit(1)
# End-def

##
 # @brief Target: print usage help.
 #
def target_help():
    print(USAGE)
# End-def

##
 # @brief Entry point: dispatch make targets.
 #
def main():
    target = sys.argv[1] if len(sys.argv) > 1 else "all"

    handlers = {
        "all": target_all,
        "clean": target_clean,
        "version": target_version,
        "sign": target_sign,
        "help": target_help,
        "-h": target_help,
        "--help": target_help,
    }

    handler = handlers.get(target)
    if handler is None:
        print("[-] Unknown target: " + target)
        print(USAGE)
        sys.exit(1)
    # End-if

    handler()
# End-def

if __name__ == "__main__":
    main()
